### ISSUE TITLE
Poor implementation of the equality and unequality operators

### ISSUE THREAD

**Issue by azubieta** [linuxdeploy/linuxdeploy-desktopfile#4]
The current implementation only compares the file paths. A better implementation would be to compare the groups, entries, and values.

**Comment by TheAssassin** [comment]
You should add examples (e.g., links to the code).

**Comment by azubieta** [comment]
My bad, here is it https://github.com/linuxdeploy/linuxdeploy-desktopfile/blob/31718acde5251855ff3931aa7ba266f5092cf45d/src/desktopfile.cpp#L173

I'm also working on this.

**Comment by TheAssassin** [comment]
Well, comparing the data _is_ comparing the entries. Nothing to fix here?

**Comment by TheAssassin** [comment]
By the way, this is covered by the tests.

https://github.com/linuxdeploy/linuxdeploy-desktopfile/blob/master/tests/test_desktopfile.cpp#L250-L275

**Comment by azubieta** [comment]
Great, closing the issue!
