### ISSUE TITLE
25f655e broke linuxdeploy CI

### ISSUE THREAD

**Issue by ids1024** [linuxdeploy/linuxdeploy-desktopfile#7]
25f655e seems to have broken the [CI build](https://github.com/linuxdeploy/linuxdeploy/actions/runs/838951405) for linuxdeploy.

In particular, changing `${TARGET_NAME}_EXCLUDE_FROM_ALL` back to `${TARGET_NAME}_EFA` makes the linuxdeploy `ci/build.sh` run without error, so presumably it's due to that.

I'm not familiar with ctest so I don't know exactly what is correct here.

**Comment by TheAssassin** [comment]
I am aware of the issue, but haven't got to fixing it in linuxdeploy as well due to some other work that had to be done first.

**Comment by TheAssassin** [comment]
Fixed: https://github.com/linuxdeploy/linuxdeploy/actions/runs/841318904

The issue was a broken variable name in a macro used in both linuxdeploy and linuxdeploy-desktopfile, which has now been corrected.
