### ISSUE TITLE
How to incorporate this? 

### ISSUE THREAD

**Issue by PublicVoidUpdate** [linuxdeploy/linuxdeploy-desktopfile#8]
I am programming a fairly simple cpp application where if i didnt have to manually parse .desktop files it would save me a lot of time, but i havent seen any documentation in the readme or any attached wikis.

**Comment by TheAssassin** [comment]
What exactly are you asking for? There is no documentation as I do not have time to provide any. Using the library is easy for people with some degree of experience with C++ under the terms of the license.

**Comment by PublicVoidUpdate** [comment]
Sorry for the delay! ive been doing research and things, so i got the
